/** CMS icon names (lucide-ish) → Ionicons glyphs. */
export const ICONS: Record<string, string> = {
  Home: 'home',
  Menu: 'restaurant',
  ShoppingBag: 'bag',
  ShoppingCart: 'cart',
  MapPin: 'location',
  Phone: 'call',
  Mail: 'mail',
  Image: 'images',
  Camera: 'camera',
  Calendar: 'calendar',
  Star: 'star',
  Heart: 'heart',
  User: 'person',
  Users: 'people',
  Settings: 'settings',
  Info: 'information-circle',
  Gift: 'gift',
  Tag: 'pricetag',
  Clock: 'time',
  Globe: 'globe',
  Search: 'search',
  Bell: 'notifications-outline',
  BellRing: 'notifications',
  MoreHorizontal: 'ellipsis-horizontal',
  Utensils: 'restaurant',
  Truck: 'car',
  Share: 'share-social',
  ExternalLink: 'open-outline',
  FileText: 'document-text',
  Trash: 'trash',
  Shield: 'shield-checkmark',
};

export const ion = (name?: string) => (ICONS[name ?? ''] ?? 'ellipse-outline') as any;
